---
title: Media Server
background:
  image: https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1920
  blur: sm
  opacity: 50
cardBlur: md
theme: dark
color: zinc
headerStyle: clean
layout:
  Media:
    style: row
    columns: 3
  Downloads:
    style: row
    columns: 2
  Management:
    style: row
    columns: 4
